// languageResponse

var languageResponseArray = [
    "language!",
    "quit that!",
    "hey, no cursing",
    "No cursing.",
    "...",
    "hey keep that to yourself",
    "please don't",
    "don't smoke cuss or chew or associate with those who do",
    "stahhp",
    "cachmeoutside how bout stop cursing.",
    "hey, no more.",
    "No.",
    "Goodnight everybody",
    "I don't want to hear that",
    "let's not",
    "hey... not while I'm around",
    "how bout no",
    "i'm still here",
    "please stop",
    "please no",
    "gross.",
    "that was uncalled for.",
    "thanks... just what was asked for",
    "LANGUAGE",
    "lAnguaGe",
    "*in captain america's voice* language",
    "language.",
    "laaanguage!!",
    ". . .",
    "please. No cursing.",
    "*cough* don't curse *cough*",
    "thanks.",
    "hmm",
    "!!",
    "let's stop that. . .",
    "*insert not in my christian server meme here*",
    "not in my christian server",
    "Knock it off",
    "Ohana means quit that",
    "you sadden my heart",
    "=(",
    "Roawr. =(",
    "Oh yeah. Just say that",
    "Hey could you not",
    "I would appreciate it if you didn't",
    "Please help keep the server clean",
    "a scout is clean",
    "A Scout is Clean",
    "just because you could doesn't mean you should",
    "You make me sad",
    "Now is not a good time for that",
    "You shouldn't say that",
    "Please don't say that",
    "That's not safe for the little ears in the backseat",
    "Maybe that wasn't the best choice of words",
    "Helloooooooo nurse",
    "Not gonna slide",
    "Your language is almost as strong as Ajax",
    "did you have to?",
    "*sigh* language",
    "*language*",
    "Grrr. No more"
];

exports.generate = function() {
  var languageResponseMath = Math.floor((Math.random () * languageResponseArray.length));
  return languageResponseArray[languageResponseMath];    
}
