//taste
var tasteArray = [
  "like a 10/10",
  "like a 9/10",
  "like a 8/10",
  "like a 7/10",
  "like a 6/10",
  "like a 5/10",
  "like a 4/10",    
  "like a 3/10",
  "like a 2/10",
  "like a 1/10",
  "like a 0/10",
  "like a 5/10",
  "like a 4/10",
  "like a 5/10",
  "like a 4/10",
  "like a big chicken",
  "wonderful",
  "like a rainbow",
  "tender and juicy",
  "a little bland",
  "a little stringy",
  "like a couch potato",
  "like a potato",
  "like a bloodsucking lawyer",
  "great",
  "icky",
  "gross",
  "funny",
  "acidic",
  "bitter",
  "cool",
  "creamy",
  "delicious",
  "gooey",
  "mild",
  "nutty",
  "peppery",
  "ripe",
  "rank",
  "salty",
  "very salty",
  "as salty as seawater",
  "as salty as a lol player",
  "savory",
  "sour",
  "spicy",
  "sticky",
  "strong",
  "sweet",
  "tangy",
  "in need of a shower",
  "tart",
  "tasty",
  "like fish",
  "fishy",
  "slimy",
  "like a giant turtle",
  "like a magical leopluradon",
  "like a t-rex",
  "like a dilophosaurus",
  "like a velociraptor",
  "like a parasaurolophus",
  "like a brachiosaurus",
  "like a gallimimus",
  "like a hadrosaur",
  "like... crab?",
  "like... a toilet",
  "kinda gross",
  "like rotten bird",
  "like my insecurities",
  "like sadness",
  "like too much minecraft",
  "like... *sigh* I don't even know. Do I have to keep tasting people?",
  "a little strange",
  "like chinese takeout",
  "like stale pizza",
  "rubber",
  "like takeout and sadness",
  "like a football",
  "like a frisbee",
  "like gym socks",
  "like how a locker room smells",
  "like hamburger meat",
  "like sausage",
  "like a hamburger patty",
  "like a big mac; supersize me!",
  "like axe bodyspay",
  "like perfume",
  "like death",
  "like a new red meat",
  "like a new white meat",
  "like fried chicken"
]
       
exports.generate = function() {
  var tasteNum = Math.floor((Math.random() * tasteArray.length));
  return tasteArray[tasteNum];
}